filer/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django.conf.urls import url

from . import settings as filer_settings
from . import views


urlpatterns = [
    url(
        filer_settings.FILER_CANONICAL_URL + r'(?P<uploaded_at>[0-9]+)/(?P<file_id>[0-9]+)/$',  # flake8: noqa
        views.canonical,
        name='canonical'
    ),
]

property/urls.py
from django.urls import path
from . import views

app_name = 'property'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>/', views.category, name='category'),
    path('category/<int:category_id>/page/<int:page_num>/',  views.category, name='page'),
    path('object/<int:object_id>', views.object, name="object"),
    path('page/<int:page_id>/', views.page, name="page"),
    path('search', views.search, name="search"),
]

webcatcms/urls.py
from django.contrib import admin
from property import views
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('property.urls')),
    #path('', views.index, name='index' ),
    path('admin/', admin.site.urls),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/neruhomist/base.html
{% load static  compress %}<!DOCTYPE html>
<html lang="uk">
<head>
<title>{% block title %}{% endblock %}</title>
<meta name="description" content="{% block meta_description %}{% endblock %}" />
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="robots" content="index,follow" />
<meta property="og:title" content="{% block og_title %}{% endblock %}" />
<meta property="og:type" content="article" />
<meta property="og:url" content="{% block base_url %}{% endblock %}" />
<meta property="og:site_name" content="{% block site_name %}{% endblock %}"/>
<meta property="og:image" content="{% block og_logo %}{% endblock %}" />
<meta property="og:description" content="{% block og_description %}{% endblock%}" />
<link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />
{% compress css file style %}
<link rel="stylesheet" href="{% static 'property/css/font-awesome/css/font-awesome.min.css'%}">
<link rel="stylesheet" href="{% static 'property/css/animate.css'%}">
<link rel="stylesheet" href="{% static 'property/css/owl.carousel.min.css'%}">
<link rel="stylesheet" href="{% static 'property/css/owl.theme.default.min.css'%}">
<link rel="stylesheet" href="{% static 'property/css/magnific-popup.css'%}">
<link rel="stylesheet" href="{% static 'property/css/bootstrap-datepicker.css'%}">
<link rel="stylesheet" href="{% static 'property/css/jquery.timepicker.css'%}">
<link rel="stylesheet" href="{% static 'property/css/flaticon.css'%}">
<link rel="stylesheet" href="{% static 'property/css/style.css'%}">
  {% endcompress %}
{% block extrastyle %}{% endblock %}
</head>
<body>
  <!-- social and phone -->
  <div class="wrap">
    <div class="container">
      <div class="row justify-content-between">
          <div class="col d-flex align-items-center">
            <p class="mb-0 phone"><img src="{% static settings.phone_1.logo %}"/><span><a href="tel:{{settings.phone_1.phone}}">{{settings.phone_1.phone}}</a></span><img src='{% static settings.phone_2.logo %}'/><span><a href="tel:{{settings.phone_2.phone}}">{{settings.phone_2.phone}}</a></span></p>
        </div>
          <div class="col d-flex justify-content-end">
            <div class="social-media">
              <p class="mb-0 d-flex">
                {% if settings.link_facebook %}
                <a href="{{settings.link_facebook}}" class="d-flex align-items-center justify-content-center"><span class="fa fa-facebook"><i class="sr-only">Facebook</i></span></a>
                {% endif %}
                {% if settings.link_instagram %}
                <a href="{{settings.link_instagram}}" class="d-flex align-items-center justify-content-center"><span class="fa fa-instagram fa-x2"><i class="sr-only">Instagram</i></span></a>
                {% endif %}
                {% if settings.link_telegram %}
                <a href="{{settings.link_telegram}}" class="d-flex align-items-center justify-content-center"><span class="fa fa-telegram"><i class="sr-only">Telegram</i></span></a>
                {% endif %}
              </p>
            </div>
          </div>
      </div>
    </div>
  </div>
  <!-- END -->
  <!-- NAV -->
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="{{base_url}}"><img src="{% static 'logo.png' %}" /></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="fa fa-bars"></span> Menu
      </button>
      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a href="{{base_url}}" class="nav-link">Головна</a></li>
          {% if categories %}
            {% for category in categories %}
            <li class="nav-item"><a href="{% url 'property:category' category.id %}" class="nav-link">{{category}}</a></li>
            {% endfor %}
          {% endif %}
          {% if pages %}
            {% for page in pages %}
              {% if page.menu %}
                <li class="nav-item"><a href="{% url 'property:page' page.id %}" class="nav-link">{{page}}</a></li>
              {% endif %}
            {% endfor %}
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <!-- END -->
  <!-- content -->
{% block content %}{% endblock %}
  <!-- END -->
  <!-- footer -->
  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-3 mb-md-0 mb-4">
          <h2 class="footer-heading">Інформація</h2>
          <ul class="list-unstyled">
            {% if pages %}
            {% for page in pages %}
              {% if page.information %}
            <li><a href="{% url 'property:page' page.id %}" class="py-1 d-block">{{page}}</a></li>
              {% endif %}
            {% endfor %}
          {% endif %}
          </ul>
        </div>
        <div class="col-md-6 col-lg-3 mb-md-0 mb-4">
          <h2 class="footer-heading">Про нас</h2>
          <ul class="list-unstyled">
            {% if pages %}
            {% for page in pages %}
              {% if page.about_as %}
            <li><a href="{% url 'property:page' page.id %}" class="py-1 d-block">{{page}}</a></li>
              {% endif %}
            {% endfor %}
          {% endif %}
          </ul>
        </div>
        <div class="col-md-6 col-lg-3 mb-md-0 mb-4">
          <h2 class="footer-heading">Контакти</h2>
          <ul class="list-unstyled">
            {% if settings.work_schedule %}
              <li><span><i class="fa fa-clock-o" aria-hidden="true"></i>{{settings.work_schedule}}</span></li>
            {% endif %}
            {% if settings.phone_1 %}
              <li><i class="fa fa-phone" aria-hidden="true"></i><a href="tel:{{settings.phone_1.phone}}">{{settings.phone_1.phone}}</a></li>
            {% endif %}
            {% if settings.phone_2 %}
              <li><i class="fa fa-phone" aria-hidden="true"></i><a href="tel:{{settings.phone_2.phone}}">{{settings.phone_2.phone}}</a></li>
            {% endif %}
            {% if settings.phone_3 %}
              <li><i class="fa fa-phone" aria-hidden="true"></i><a href="tel:{{settings.phone_3.phone}}">{{settings.phone_3.phone}}</a></li>
            {% endif %}
            {% if settings.phone_4 %}
              <li><i class="fa fa-phone" aria-hidden="true"></i><a href="tel:{{settings.phone_4.phone}}">{{settings.phone_4.phone}}</a></li>
            {% endif %}
            {% if settings.email_1 %}
              <li><span><i class="fa fa-envelope-o" aria-hidden="true"></i>{{settings.email_1}}</span></li>
            {% endif %}
            {% if settings.email_2 %}
              <li><span><i class="fa fa-envelope-o" aria-hidden="true"></i>{{settings.email_2}}</span></li>
            {% endif %}
          </ul>
        </div>
        <div class="col-md-6 col-lg-3 mb-md-0 mb-4">
          <h3 class="footer-heading">Ми в соц. мережах</h3>
          <ul class="ftco-footer-social p-0">
            {% if settings.link_facebook %}
              <li class="ftco-animate"><a href="{{settings.link_facebook}}" data-toggle="tooltip" data-placement="top" title="Facebook"><span class="fa fa-facebook"></span></a></li>
            {% endif %}
            {% if settings.link_instagram %}
              <li class="ftco-animate"><a href="{{settings.link_instagram}}" data-toggle="tooltip" data-placement="top" title="Instagram"><span class="fa fa-instagram"></span></a></li>
            {% endif %}
            {% if settings.link_telegram %}
              <li class="ftco-animate"><a href="{{settings.link_telegram}}" data-toggle="tooltip" data-placement="top" title="Telegram"><span class="fa fa-telegram"></span></a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
    <div class="w-100 mt-5 border-top py-5">
      <div class="container">
        <div class="row">
          <div>
            <p class="copyright mb-0">&copy;<script>document.write(new Date().getFullYear());</script> Всі права захищені | Розроблено на <i class="fa fa-rocket" aria-hidden="true"></i> <a href="#" target="_blank">webcatcms</a></p>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- END -->
  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>
  <!-- END -->
  {% compress js file all %}
  <script src="{% static 'property/js/jquery.min.js'%}"></script>
  <script src="{% static 'property/js/jquery-migrate-3.0.1.min.js'%}"></script>
  <script src="{% static 'property/js/popper.min.js'%}"></script>
  <script src="{% static 'property/js/bootstrap.min.js'%}"></script>
  <script src="{% static 'property/js/jquery.easing.1.3.js'%}"></script>
  <script src="{% static 'property/js/jquery.waypoints.min.js'%}"></script>
  <script src="{% static 'property/js/jquery.stellar.min.js'%}"></script>
  <script src="{% static 'property/js/jquery.animateNumber.min.js'%}"></script>
  <script src="{% static 'property/js/bootstrap-datepicker.js'%}"></script>
  <script src="{% static 'property/js/jquery.timepicker.min.js'%}"></script>
  <script src="{% static 'property/js/owl.carousel.min.js'%}"></script>
  <script src="{% static 'property/js/jquery.magnific-popup.min.js'%}"></script>
  <script src="{% static 'property/js/scrollax.min.js'%}"></script>
  <script src="{% static 'property/js/google-map.js'%}"></script>
  {% endcompress %}
   <script>
  $("#ot").click(function () {
      $(this).change(function () {
          $.ajax(function () {
            url: {% url 'property:search' %} ,
            data: {json: jsondata},
            contentType: "application/json",
            success: function(data) {
                alert(JSON.stringify(data);)
              }
          });

      });

                });
  </script>
  <script src="{% static 'property/js/main.js'%}"></script>
{% block js %}{% endblock %}



  </body>
</html>

templates/neruhomist/index.html
{% extends "neruhomist/base.html" %}
{% load static %}
{% block title %}{{settings.title}}{% endblock %}
{% block meta_description %}{{settings.meta_description}}{% endblock %}
{% block og_title %}{{settings.title}}{% endblock %}
{% block site_name %}{{settings.title}}{% endblock %}
{% block base_url %}{{base_url}}{% endblock %}
{% block og_logo %}{{base_url}}/static/logo.png{% endblock %}
{% block og_description %}{{settings.meta_description}}{% endblock %}
{% block content %}
<!-- image site -->
    <div class="hero-wrap js-fullheight" style="background-image: url('{{settings.site_image.url}}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start" data-scrollax-parent="true"></div>
      </div>
    </div>
<!-- END -->
<!-- search -->
    <section class="ftco-section ftco-book ftco-no-pt ftco-no-pb">
      <div class="container">
        <div class="row justify-content-end">
          <div class="col-lg-4">
            <form action="#" class="appointment-form">
              {% csrf_token %}
              <!--<h3 class="mb-3">Пошук нерухомості</h3>-->
              <div class="row">
                <div class="col-md-12">
                   <div class="form-group">
                    <div class="form-field">
                      <div class="select-wrap">
                        <div class="icon"><span class="fa fa-chevron-down"></span></div>
                        <select name="" id="ot" class="form-control">
                          <option value="">Тип Об'єкту:</option>
                          {% if object_type %}
                              {% for type in object_type %}
                                  <option value="{{ type }}">{{ type }}</option>
                              {% endfor %}
                          {% endif %}
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <div class="input-wrap">
                      <div class="icon"><span class="ion-md-calendar"></span></div>
                      <input type="text" class="form-control appointment_date-check-in" placeholder="Check-In">
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <div class="input-wrap">
                      <div class="icon"><span class="ion-md-calendar"></span></div>
                      <input type="text" class="form-control appointment_date-check-out" placeholder="Check-Out">
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <div class="form-field">
                      <div class="select-wrap">
                        <div class="icon"><span class="fa fa-chevron-down"></span></div>
                        <select name="" id="" class="form-control">
                          <option value="">Adults</option>
                          <option value="">1</option>
                          <option value="">2</option>
                          <option value="">3</option>
                          <option value="">4</option>
                          <option value="">5</option>
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <div class="form-field">
                      <div class="select-wrap">
                        <div class="icon"><span class="fa fa-chevron-down"></span></div>
                        <select name="" id="" class="form-control">
                          <option value="">Children</option>
                          <option value="">1</option>
                          <option value="">2</option>
                          <option value="">3</option>
                          <option value="">4</option>
                          <option value="">5</option>
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Phone number">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <div class="input-wrap">
                      <div class="icon"><span class="ion-ios-clock"></span></div>
                      <input type="text" class="form-control appointment_time" placeholder="Time">
                    </div>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <input type="submit" value="Знайти" class="btn btn-primary py-3 px-4">
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
<!-- END -->
<!-- Categories -->
    <section class="ftco-section ftco-services bg-light">
    	<div class="container">
    		<div class="row">
        {% for category in categories %}
          <div class="col-md-4 d-flex services align-self-stretch px-4 ftco-animate">
            <div class="d-block services-wrap text-center">
            <div class="hovereffect">
                <img class="img-responsive" src="{{category.image.url}}" alt="">
                <div class="overlay">
                   <h2>{{ category.title }}</h2>
                   <a class="info" href="{% url 'property:category' category.id %}">Дивитись</a>
                </div>
            </div>
          </div>
        </div>
        {% endfor %}
        </div>
    	</div>
    </section>
<!-- END Categories-->
<!-- slider recommended objects -->
<section class="ftco-section testimony-section bg-light">
  <div class="container">
    <div class="row justify-content-center pb-5 mb-3">
      <div class="col-md-12 heading-section text-center ftco-animate">
        <h3>Нерухомість онлайн РЕКОМЕНДУЄ</h3>
      </div>
    </div>
    <div class="row ftco-animate">
      <div class="col-md-12">
        <div class="carousel-testimony owl-carousel">

          {% for r in recommended %}
          <div class="item ">
<div class="testimony-wrap d-flex">
            <div class="hovereffect">
                <img class="img-responsive" src="{{r.image.url}}" alt="">
                <p>{{r.title}}</p>
                <div class="overlay">
                   <a class="info" href="{% url 'property:object' r.id %}">Дивитись</a>
                </div>
            </div>

</div>

          </div>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
</section>
<!-- END -->
{% endblock %}

templates/neruhomist/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

templates/neruhomist/object.html
{% extends "neruhomist/base.html" %}
{% load static %}
{% load thumbnail %}
{% block title %}{{object.title}}{% endblock %}
{% block meta_description %}{{object.meta_description}}{% endblock %}
{% block og_title %}{{object.title}}{% endblock %}
{% block site_name %}{{object.title}}{% endblock %}
{% block base_url %}{{base_url}}{% endblock %}
{% block og_logo %}{{base_url}}static/logo.png{% endblock %}
{% block og_description %}{{object.meta_description}}{% endblock %}
{% block extrastyle %}
<link rel="stylesheet" href="{% static 'property/css/royalslider.css'%}">
{% endblock %}
{% block content %}

<section>
			<div class="container">
				<div class="row no-gutters">
					<div class="col-md-12">
						<p class="breadcrumbs mb-2">
						<span><a href="{{base_url}}">Головна  <i class="fa fa-chevron-right"></i></a></span>
						<span><a href="{% url 'property:category' object.category_object.id %}">{{object.category_object}}  <i class="fa fa-chevron-right"></i></a></span>
						<span>{{object}}  <i class="fa fa-chevron-right"></i></span>
						</p>
					</div>
					<div class="col-md-6 wrap-about">
						<div  class="page wrapper main-wrapper">
							<div class="row clearfix">
								<div class="col span_4 fwImage">
									<div id="gallery-1" class="royalSlider rsDefault">
    									<a class="rsImg" data-rsw="590" data-rsh="450"  data-rsBigImg="{{object.image.url}}" href="{{object.image.url}}"><img width="96" height="72" class="rsTmb" src="{{object.image.url}}" /></a>
										{% if images %}
											{% for image in images %}
	 									 		<a class="rsImg" data-rsw="590" data-rsh="450"  data-rsBigImg="{{image.image.url}}" href="{{image.image.url}}"><img width="96" height="72" class="rsTmb" src="{{image.image.url}}" /></a>
											{% endfor %}
										{% endif %}
  									</div>
								</div>
							</div>
  						</div>
					</div>
					<div class="col-md-6 wrap-about ftco-animate">
	          <div class="heading-section">
	          	<div class="pl-md-5">
		            <h4>{{object.title}}</h4>
	            </div>
	          </div>
	          <div class="pl-md-5">
				  <div class="row">
					{% if object.locality %}
		            <div class="services-2 col-lg-6 d-flex w-100">
		              <div class="icon d-flex justify-content-center align-items-center">
		            		<span class="flaticon-pin-1"></span>
		              </div>
		              <div class="media-body pl-3">
		                <h3 class="heading">Населенный пункт:</h3>
		                <p>{{object.locality}}</p>
		              </div>
		            </div>
					{% endif %}
					{% if object.area %}
		            <div class="services-2 col-lg-6 d-flex w-100">
		              <div class="icon d-flex justify-content-center align-items-center">
		            		<span class="flaticon-pin-2"></span>
		              </div>
		              <div class="media-body pl-3">
		                <h3 class="heading">Район/Массив:</h3>
		                <p>{{object.area}}</p>
		              </div>
		            </div>
					{% endif %}
					{% if object.street %}
		            <div class="services-2 col-lg-6 d-flex w-100">
		              <div class="icon d-flex justify-content-center align-items-center">
		            		<span class="flaticon-pin"></span>
		              </div>
		              <div class="media-body pl-3">
		                <h3 class="heading">Вулиця:</h3>
		                <p>{{object.street}}</p>
		              </div>
		            </div>
					{% endif %}
					{% if object.rooms %}
		            <div class="services-2 col-lg-6 d-flex w-100">
		              <div class="icon d-flex justify-content-center align-items-center">
		            		<span class="flaticon-house"></span>
		              </div>
		              <div class="media-body pl-3">
		                <h3 class="heading">Кількість кімнат:</h3>
		                <p>{{object.rooms}}</p>
		              </div>
		            </div>
					{% endif %}
					{% if object.total_space %}
		            <div class="services-2 col-lg-6 d-flex w-100">
		              <div class="icon d-flex justify-content-center align-items-center">
		            		<span class="flaticon-house"></span>
		              </div>
		              <div class="media-body pl-3">
		                <h3 class="heading">Загальна площа:</h3>
		                <p>{{object.total_space}} m2</p>
		              </div>
		            </div>
					{% endif %}
					{% if object.living_space %}
		            <div class="services-2 col-lg-6 d-flex w-100">
		              <div class="icon d-flex justify-content-center align-items-center">
		            		<span class="flaticon-house"></span>
		              </div>
		              <div class="media-body pl-3">
		                <h3 class="heading">Житлова площа:</h3>
		                <p>{{object.living_space}} m2</p>
		              </div>
		            </div>
					{% endif %}
					{% if object.kitchen_space %}
		            <div class="services-2 col-lg-6 d-flex w-100">
		              <div class="icon d-flex justify-content-center align-items-center">
		            		<span class="flaticon-house"></span>
		              </div>
		              <div class="media-body pl-3">
		                <h3 class="heading">Кухня площа:</h3>
		                <p>{{object.kitchen_space}} m2</p>
		              </div>
		            </div>
					{% endif %}
					{% if object.height %}
		            <div class="services-2 col-lg-6 d-flex w-100">
		              <div class="icon d-flex justify-content-center align-items-center">
		            		<span class="flaticon-house"></span>
		              </div>
		              <div class="media-body pl-3">
		                <h3 class="heading">Висота стелі:</h3>
		                <p>{{object.height}} m</p>
		              </div>
		            </div>
					{% endif %}
					{% if object.floor %}
		            <div class="services-2 col-lg-6 d-flex w-100">
		              <div class="icon d-flex justify-content-center align-items-center">
		            		<span class="flaticon-apartment-1"></span>
		              </div>
		              <div class="media-body pl-3">
		                <h3 class="heading">Поверх:</h3>
		                <p>{{object.floor}}</p>
		              </div>
		            </div>
					{% endif %}
					{% if object.storeys %}
		            <div class="services-2 col-lg-6 d-flex w-100">
		              <div class="icon d-flex justify-content-center align-items-center">
		            		<span class="flaticon-apartment"></span>
		              </div>
		              <div class="media-body pl-3">
		                <h3 class="heading">Поверховість:</h3>
		                <p>{{object.storeys}}</p>
		              </div>
		            </div>
					{% endif %}
					{% if object.price %}
					 <div class="services-2 col-lg-6 d-flex w-100">
		              <div class="icon d-flex justify-content-center align-items-center">
		            		<span class="flaticon-money"></span>
		              </div>
		              <div class="media-body pl-3">
		                <h3 class="heading">Вартість:</h3>
		                <p>{{object.price}} $</p>
		              </div>
		            </div>
					{% endif %}


		          </div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section>
			<div class="container">
				<div class="row no-gutters">
				<p class="description">Опис</p>
				{% autoescape off %}
					{{object.description}}
				{% endautoescape %}
				</div>
			</div>
		</section>
		{% if interested %}
		<section class="ftco-section testimony-section">
  <div class="container">
    <div class="row justify-content-center pb-5 mb-3">
      <div class="col-md-12 heading-section text-center ftco-animate">
        <h3>Це може вас зацікавити</h3>
      </div>
    </div>
    <div class="row ftco-animate">
      <div class="col-md-12">
        <div class="carousel-testimony owl-carousel">

          {% for i in interested %}
          <div class="item ">
<div class="testimony-wrap d-flex">
            <div class="hovereffect">
                <img class="img-responsive" src="{{i.image.url}}" alt="">
                <p>{{i.title}}</p>
                <div class="overlay">
                   <a class="info" href="{% url 'property:object' i.id %}">Дивитись</a>
                </div>
            </div>

</div>

          </div>
          {% endfor %}


        </div>
      </div>
    </div>
  </div>
</section>
		{% endif %}
{% endblock %}
{% block js %}
<script src="{% static 'property/js/jquery.royalslider.min.js'%}"></script>
    <script>
    	 $(document).ready(function() {
           $('#gallery-1').royalSlider({
    fullscreen: {
      enabled: true,
      nativeFS: true
    },
    controlNavigation: 'thumbnails',
    autoScaleSlider: true,
    autoScaleSliderWidth: 960,
    autoScaleSliderHeight: 850,
    loop: false,
    imageScaleMode: 'fit-if-smaller',
    navigateByClick: true,
    numImagesToPreload:2,
    arrowsNav:true,
    arrowsNavAutoHide: true,
    arrowsNavHideOnTouch: true,
    keyboardNavEnabled: true,
    fadeinLoadedSlide: true,
    globalCaption: false,
    globalCaptionInside: false,
    thumbs: {

      arrowsAutoHide: true,
      appendSpan: true,
      firstMargin: true,
      paddingBottom: 1
    }
  });
		});
    </script>
{% endblock %}

templates/neruhomist/page.html
{% extends "neruhomist/base.html" %}
{% load static %}
{% load thumbnail %}
{% block title %}{{page.title}}{% endblock %}
{% block meta_description %}{{page.meta_description}}{% endblock %}
{% block og_title %}{{page.title}}{% endblock %}
{% block site_name %}{{page.title}}{% endblock %}
{% block base_url %}{{base_url}}{% endblock %}
{% block og_logo %}{{base_url}}static/logo.png{% endblock %}
{% block og_description %}{{page.meta_description}}{% endblock %}
{% block content %}

		<section>
			<div class="container">
				<div class="row no-gutters">
				<p class="description">Опис</p>
				{% autoescape off %}
					{{page.description}}
				{% endautoescape %}
				</div>
			</div>
		</section>

{% endblock %}
{% block js %}
{% endblock %}